import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Menu } from "antd";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <div className="w-full">
          <Menu
            direction="ltr"
            mode="horizontal"
            items={[
              { key: "/", label: <Link href="/">Home</Link> },
              {
                key: "/copywriting",
                label: <Link href="/copywriting">Copywriting</Link>,
              },
            ]}
          />
        </div>
        <div className="p-4 h-full w-full">{children}</div>
      </body>
    </html>
  );
}
