import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Menu } from "antd";
import "./globals.css";
import { SDKInitializer } from "./components/sdk-initializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <SDKInitializer />
        <div className="flex h-full w-full">
          <Menu
            mode="vertical"
            items={[
              { key: "/", label: <Link href="/">Home</Link> },
              {
                key: "/copywriting",
                label: <Link href="/copywriting">Copywriting</Link>,
              },
              {
                key: "/monitor-platform",
                label: "Monitor Platform",
                children: [
                  {
                    key: "monitor-platform/test-collect-sdk",
                    label: (
                      <Link href="/monitor-platform/test-collect-sdk">
                        Test Collect SDK
                      </Link>
                    ),
                  },
                ],
              },
            ]}
          />
          <div className="p-4 h-full w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
