import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Menu, Layout, Flex } from "antd";
import "./globals.css";
import { SDKInitializer } from "./components/sdk-initializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const { Content, Sider } = Layout;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <SDKInitializer />
        <Flex flex={1} gap={12}>
          <Menu
            style={{ width: "240px" }}
            mode="vertical"
            items={[
              { key: "/", label: <Link href="/">Home</Link> },
              {
                key: "/copywriting",
                label: <Link href="/copywriting">Copywriting</Link>,
              },
              {
                key: "/monitor-platform",
                label: "Monitor Platform",
                children: [
                  {
                    key: "monitor-platform/test-collect-sdk",
                    label: (
                      <Link href="/monitor-platform/test-collect-sdk">
                        Test Collect SDK
                      </Link>
                    ),
                  },
                ],
              },
              {
                key: "/dianping",
                label: <div>用户点评项目（练习redis）</div>,
                children: [
                  {
                    key: "/dianping/home",
                    label: <Link href="/dianping/home">首页</Link>,
                  },
                  {
                    key: "/dianping/list",
                    label: <Link href="/dianping/list">商户列表</Link>,
                  },
                  {
                    key: "/dianping/login",
                    label: <Link href="/dianping/login">登录</Link>,
                  },
                  {
                    key: "/dianping/me",
                    label: <Link href="/dianping/me">我的页面</Link>,
                  },
                ],
              },
            ]}
          />
          <div style={{ width: "calc(100% - 240px)", padding: 12 }}>
            {children}
          </div>
        </Flex>

        {/* <div className="flex h-full">
          <div className="p-4 h-full flex-1">{children}</div>
        </div> */}
      </body>
    </html>
  );
}
